name: CI Workflow
on: [ push ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Make
        run: make -j2 clean all test
      - name: Upload test executable
        uses: actions/upload-artifact@v3
        with:
          name: fperf_test
          path: build/fperf_test
  test:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v3
        with:
          name: fperf_test
      - name: Making test artifact executable
        run: chmod +x fperf_test
      - name: Run tests
        run: ./fperf_test
