name: CI Workflow
on: [ push ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Make
        run: make clean all test
      - name: Upload tests executable
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: build/tests
  test:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Download autoperf artifact
        uses: actions/download-artifact@v3
        with:
          name: tests
      - name: Making artifact executable
        run: chmod +x ./tests
      - name: Run tests
        run: ./tests
