name: CI Workflow
on: [ push ]
jobs:
  format:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Check format
        run: make check-format
  build:
    runs-on: self-hosted
    needs: [ format ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Make
        run: make -j2 clean all build/fperf_test
      - name: Upload fperf executable
        uses: actions/upload-artifact@v3
        with:
          name: fperf
          path: build/fperf
      - name: Upload unit test executable
        uses: actions/upload-artifact@v3
        with:
          name: fperf_test
          path: build/fperf_test
  unit-test:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v3
        with:
          name: fperf_test
      - name: Making test artifact executable
        run: chmod +x fperf_test
      - name: Run tests
        run: ./fperf_test
  e2e-test:
    runs-on: self-hosted
    needs: [ build, unit-test ]
    steps:
      - name: Download fperf artifact
        uses: actions/download-artifact@v3
        with:
          name: fperf
      - name: Making fperf artifact executable
        run: chmod +x fperf
      - name: Run the fperf
        run: ./fperf rr

