name: CI Workflow
on: [ push ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Make
        run: make -j2 clean all build/autoperf_test
      - name: Upload autoperf executable
        uses: actions/upload-artifact@v3
        with:
          name: autoperf
          path: build/autoperf
      - name: Upload unit test executable
        uses: actions/upload-artifact@v3
        with:
          name: autoperf_test
          path: build/autoperf_test
  unit-test:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v3
        with:
          name: autoperf_test
      - name: Making test artifact executable
        run: chmod +x autoperf_test
      - name: Run tests
        run: ./autoperf_test
  e2e-test:
    runs-on: self-hosted
    needs: [ build, unit-test ]
    steps:
      - name: Download autoperf artifact
        uses: actions/download-artifact@v3
        with:
          name: autoperf
      - name: Making autoperf artifact executable
        run: chmod +x autoperf
      - name: Run the autoperf
        run: ./autoperf rr

